version: '3'
networks:
    mvp_net:
      ipam:
        driver: default
        config:
          - subnet: 172.172.0.0/16


volumes:
    artifactory_data:
    jenkins_data:
    jenkins_agent_data:


services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
    container_name: artifactory
    ports:
     - 8098:8081
    volumes:
     - artifactory_data:/var/opt/jfrog/artifactory
    environment:
     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx512m
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      mvp_net:
        ipv4_address: 172.172.0.10

  jenkinsmaster:
    build:
      context: ./jenkins_master_build
      args:
        - HOST_DOCKER_GID=999
    image: jenkins-master:v1
    container_name: jenkinsmaster_mvp
#    env_file:
#      - jenkins.env
    environment:
     - JAVA_OPTS=-Xmx1g -Djenkins.install.runSetupWizard=false
    labels:
      lab.at.description: "Jenkins master"
#    privileged: true
#    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenkinsmaster_mvp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
    networks:
      mvp_net:
        ipv4_address: 172.172.0.20
  
  
  jenkinsagent:
    build:
      context: ./jenkins_agent_build
    image: jenkins-agent:v1
    container_name: jenkinsagent_mvp
 
    labels:
      lab.at.description: "Jenkins ssh agent"
#    privileged: true
#    user: root
    volumes:
      - jenkins_agent_data:/buildroot
    ports:
        - 2222:0022
    networks:
      mvp_net:
        ipv4_address: 172.172.0.21
